package com.redhat.demos.dm.loan.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Credit Score")
	private int creditScore;

	private java.lang.Character ss;

	private java.lang.String adam;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(int creditScore) {
		this.creditScore = creditScore;
	}

	public java.lang.Character getSs() {
		return this.ss;
	}

	public void setSs(java.lang.Character ss) {
		this.ss = ss;
	}

	public java.lang.String getAdam() {
		return this.adam;
	}

	public void setAdam(java.lang.String adam) {
		this.adam = adam;
	}

	public Applicant(java.lang.String name, int creditScore,
			java.lang.Character ss, java.lang.String adam) {
		this.name = name;
		this.creditScore = creditScore;
		this.ss = ss;
		this.adam = adam;
	}

}